### importing pandas

In [1]:
import pandas as pd

### DataFrame()

In [2]:
pd.DataFrame({'Yes':[50, 21], 'No':[131, 2]})

   Yes   No
0   50  131
1   21    2

In [3]:
pd.DataFrame({'Bob':['I liked it.', 'It was awful.'], 'Sue':['Pretty good.','Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [4]:
pd.DataFrame({'Bob':['I liked it.', 'It was awful.'], 'Sue':['Pretty good.','Bland.']}, index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

### Series()

In [5]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

### pandas.read_csv(), DataFrame.shape, DataFrame.head()

In [7]:
wine_reviews = pd.read_csv("datasets/wines/winemag-data-130k-v2.csv")
wine_reviews.shape

(129971, 14)

In [8]:
wine_reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [9]:
reviews = pd.read_csv("datasets/wines/winemag-data-130k-v2.csv", index_col=0)
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### indexing in pandas

In [10]:
reviews.country

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [11]:
reviews['country']

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [12]:
reviews['country'][0]

'Italy'

### iloc

In [13]:
reviews.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [14]:
reviews.iloc[:, 0]

0            Italy
1         Portugal
2               US
3               US
4               US
            ...
129966     Germany
129967          US
129968      France
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [15]:
reviews.iloc[:3, 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [16]:
reviews.iloc[1:3, 0]

1    Portugal
2          US
Name: country, dtype: object

In [17]:
reviews.iloc[[0, 1, 2], 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [18]:
reviews[-5:]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### loc

In [19]:
reviews.loc[0, 'country']

'Italy'

In [20]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

               taster_name taster_twitter_handle  points
0            Kerin O’Keefe          @kerinokeefe      87
1               Roger Voss            @vossroger      87
2             Paul Gregutt           @paulgwine       87
3       Alexander Peartree                   NaN      87
4             Paul Gregutt           @paulgwine       87
...                    ...                   ...     ...
129966  Anna Lee C. Iijima                   NaN      90
129967        Paul Gregutt           @paulgwine       90
129968          Roger Voss            @vossroger      90
129969          Roger Voss            @vossroger      90
129970          Roger Voss            @vossroger      90

[129971 rows x 3 columns]

### set_index()

In [21]:
reviews.set_index("title")

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,variety,winery
title,,,,,,,,,,,,
Nicosia 2013 Vulkà Bianco (Etna),Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,White Blend,Nicosia
Quinta dos Avidagos 2011 Avidagos Red (Douro),Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Portuguese Red,Quinta dos Avidagos
Rainstorm 2013 Pinot Gris (Willamette Valley),US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Gris,Rainstorm
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore),US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,Riesling,St. Julian
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley),US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel),Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
Citation 2004 Pinot Noir (Oregon),US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Pinot Noir,Citation
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace),France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Gresser
Domaine Marcel Deiss 2012 Pinot Gris (Alsace),France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Pinot Gris,Domaine Marcel Deiss
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace),France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Gewürztraminer,Domaine Schoffit

### applying conditions

In [22]:
reviews.country == 'Italy'

0          True
1         False
2         False
3         False
4         False
          ...
129966    False
129967    False
129968    False
129969    False
129970    False
Name: country, Length: 129971, dtype: bool

In [23]:
reviews.loc[reviews.country == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [24]:
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129929,Italy,"This luminous sparkler has a sweet, fruit-forw...",NaN,91,38.0,Veneto,Prosecco Superiore di Cartizze,NaN,NaN,NaN,Col Vetoraz Spumanti NV Prosecco Superiore di...,Prosecco,Col Vetoraz Spumanti
129943,Italy,"A blend of Nero d'Avola and Syrah, this convey...",Adènzia,90,29.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio del Cristo di Campobello 2012 Adènzia R...,Red Blend,Baglio del Cristo di Campobello
129947,Italy,"A blend of 65% Cabernet Sauvignon, 30% Merlot ...",Symposio,90,20.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O’Keefe,@kerinokeefe,Feudo Principi di Butera 2012 Symposio Red (Te...,Red Blend,Feudo Principi di Butera
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

In [25]:
reviews.loc[(reviews.country == 'Italy') | (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [26]:
reviews.loc[reviews.country.isin(['Italy', 'France'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129964,France,"Initially quite muted, this wine slowly develo...",Domaine Saint-Rémy Herrenweg,90,NaN,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Ehrhart 2013 Domaine Saint-Rémy Herren...,Gewürztraminer,Domaine Ehrhart
129965,France,"While it's rich, this beautiful dry wine also ...",Seppi Landmann Vallée Noble,90,28.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Rieflé-Landmann 2013 Seppi Landmann Va...,Pinot Gris,Domaine Rieflé-Landmann
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [27]:
reviews.loc[reviews.price.notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [28]:
reviews['critic'] = 'everyone'
reviews['critic']

0         everyone
1         everyone
2         everyone
3         everyone
4         everyone
            ...
129966    everyone
129967    everyone
129968    everyone
129969    everyone
129970    everyone
Name: critic, Length: 129971, dtype: object

In [29]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0         129971
1         129970
2         129969
3         129968
4         129967
           ...
129966         5
129967         4
129968         3
129969         2
129970         1
Name: index_backwards, Length: 129971, dtype: int32

### quick statistical inference

In [30]:
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [31]:
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [32]:
reviews.points.mean()

88.44713820775404

In [33]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [34]:
reviews.taster_name.value_counts()

Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: taster_name, dtype: int64

In [35]:
review_points_mean = reviews.points.mean()

### map()

In [36]:
reviews.points.map(lambda p:p - review_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [37]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row
    
reviews.apply(remean_points, axis='columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),everyone,5
129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,everyone,4
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,everyone,3
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [38]:
reviews.head(1)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971

In [39]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [40]:
reviews.country +" - "+ reviews.region_1

0                     Italy - Etna
1                              NaN
2           US - Willamette Valley
3         US - Lake Michigan Shore
4           US - Willamette Valley
                    ...
129966                         NaN
129967                 US - Oregon
129968             France - Alsace
129969             France - Alsace
129970             France - Alsace
Length: 129971, dtype: object

### groupby()

In [41]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [42]:
reviews.groupby('points').price.min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

In [43]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [44]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
Armenia   Armenia             Armenia
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery  \
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

                              critic  index_backwards
country   province
Argentina Mendoza Province  everyone            47217
          Other             everyone            51668
Armenia   Armenia           everyone            63825
Australia Australia Other   everyone            92089
          New South Wales   everyone            44634
...                              ...              ...
Uruguay   Juanico           everyone           120838
          Montevideo        everyone           114221
          Progreso          everyone            36868
          San Jose          everyone            90073
          Uruguay           everyone            90610

[425 rows x 15 columns]

In [45]:
reviews.groupby(['country']).price.agg([len, min, max])

                            len   min     max
country
Argentina                3800.0   4.0   230.0
Armenia                     2.0  14.0    15.0
Australia                2329.0   5.0   850.0
Austria                  3345.0   7.0  1100.0
Bosnia and Herzegovina      2.0  12.0    13.0
Brazil                     52.0  10.0    60.0
Bulgaria                  141.0   8.0   100.0
Canada                    257.0  12.0   120.0
Chile                    4472.0   5.0   400.0
China                       1.0  18.0    18.0
Croatia                    73.0  12.0    65.0
Cyprus                     11.0  11.0    21.0
Czech Republic             12.0  15.0    45.0
Egypt                       1.0   NaN     NaN
England                    74.0  25.0    95.0
France                  22093.0   5.0  3300.0
Georgia                    86.0   9.0    40.0
Germany                  2165.0   5.0   775.0
Greece                    466.0   8.0    79.0
Hungary                   146.0  10.0   764.0
India                       9.0  10.0    20.0
Israel                    505.0   8.0   150.0
Italy                   19540.0   5.0   900.0
Lebanon                    35.0  13.0    75.0
Luxembourg                  6.0  16.0    30.0
Macedonia                  12.0  15.0    20.0
Mexico                     70.0   8.0   108.0
Moldova                    59.0   8.0    42.0
Morocco                    28.0  14.0    40.0
New Zealand              1419.0   7.0   130.0
Peru                       16.0  10.0    68.0
Portugal                 5691.0   5.0  1000.0
Romania                   120.0   4.0   320.0
Serbia                     12.0  15.0    42.0
Slovakia                    1.0  16.0    16.0
Slovenia                   87.0   7.0    90.0
South Africa             1401.0   5.0   330.0
Spain                    6645.0   4.0   770.0
Switzerland                 7.0  21.0   160.0
Turkey                     90.0  14.0   120.0
US                      54504.0   4.0  2013.0
Ukraine                    14.0   6.0    13.0
Uruguay                   109.0  10.0   130.0

In [46]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [47]:
mi = countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [48]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

### sort_values()

In [49]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

          country               province    len
179        Greece  Muscat of Kefallonian      1
192        Greece          Sterea Ellada      1
194        Greece                 Thraki      1
354  South Africa             Paardeberg      1
40         Brazil       Serra do Sudeste      1
..            ...                    ...    ...
409            US                 Oregon   5373
227         Italy                Tuscany   5897
118        France               Bordeaux   5941
415            US             Washington   8639
392            US             California  36247

[425 rows x 3 columns]

In [50]:
countries_reviewed.sort_values(by='len', ascending=False)

          country         province    len
392            US       California  36247
415            US       Washington   8639
118        France         Bordeaux   5941
227         Italy          Tuscany   5897
409            US           Oregon   5373
..            ...              ...    ...
101       Croatia              Krk      1
247   New Zealand        Gladstone      1
357  South Africa  Piekenierskloof      1
63          Chile          Coelemu      1
149        Greece           Beotia      1

[425 rows x 3 columns]

### sort_index()

In [51]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [52]:
countries_reviewed.sort_values(by=['country', 'len'])

       country          province   len
1    Argentina             Other   536
0    Argentina  Mendoza Province  3264
2      Armenia           Armenia     2
6    Australia          Tasmania    42
4    Australia   New South Wales    85
..         ...               ...   ...
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
420    Uruguay           Juanico    12
424    Uruguay           Uruguay    24
419    Uruguay         Canelones    43

[425 rows x 3 columns]

### dtype

In [53]:
reviews.price.dtype

dtype('float64')

In [54]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
critic                    object
index_backwards            int32
dtype: object

In [55]:
reviews.points.astype('float64')

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

In [56]:
reviews.index.dtype

dtype('int64')

In [57]:
reviews[pd.isnull(reviews.country)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines,everyone,129058
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier,everyone,126840
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking,everyone,125728
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis,everyone,120462
9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi,everyone,120221
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy,everyone,5795
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho,everyone,564
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho,everyone,563
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ,everyone,381
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot,everyone,71

In [58]:
reviews.region_2.fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

In [59]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0             @kerino
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

### rename()

In [60]:
reviews.rename(columns={'points': 'score'})

,country,description,designation,score,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),everyone,5
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,everyone,4
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,everyone,3
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [61]:
reviews.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
firstEntry,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
secondEntry,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),everyone,5
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,everyone,4
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,everyone,3
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

In [62]:
reviews.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
wines,,,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,129971
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,129970
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,129969
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,129968
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,129967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef),everyone,5
129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation,everyone,4
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser,everyone,3
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,everyone,2
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,everyone,1

### combining datasets

In [63]:
canadian_youtube = pd.read_csv("datasets/youtube/CAvideos.csv")
british_youtube = pd.read_csv("datasets/youtube/GBvideos.csv")

pd.concat([canadian_youtube, british_youtube])

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

In [64]:
left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK')

                                                                 video_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       PNn8sECd7io
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       DvPW66IFhMI
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       EXEaMjFeiEk
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       bYvQmusLaxw
                                                   17.21.12       bYvQmusLaxw
...                                                                       ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       WttN1Z0XF4k
                                                   18.29.04       WttN1Z0XF4k
                                                   18.30.04       WttN1Z0XF4k
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Wt9Gkpmbt44
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Az72jrKbANA

                                                                                channel_title_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                            Markiplier
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        AlexRamiGaming
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        AlexRamiGaming
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                  Pure Living for Life
                                                   17.21.12                  Pure Living for Life
...                                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                          How Talented
                                                   18.29.04                          How Talented
                                                   18.30.04                          How Talented
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                         TheBigJackpot
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       Right Side Broadcasting Network

                                                                  category_id_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    20
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    20
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    20
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    24
                                                   17.21.12                    24
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    24
                                                   18.29.04                    24
                                                   18.30.04                    24
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    24
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    25

                                                                          publish_time_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       2018-01-03T19:33:53.000Z
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       2018-03-09T07:15:52.000Z
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       2018-03-10T06:26:17.000Z
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       2017-12-20T02:49:11.000Z
                                                   17.21.12       2017-12-20T02:49:11.000Z
...                                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       2018-04-28T19:40:58.000Z
                                                   18.29.04       2018-04-28T19:40:58.000Z
                                                   18.30.04       2018-04-28T19:40:58.000Z
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       2018-05-07T06:58:59.000Z
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       2018-04-03T23:12:37.000Z

                                                                                                           tags_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       getting over it|"markiplier"|"funny moments"|"...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       PS4 Battle Royale|"PS4 Pro Battle Royale"|"Bat...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       timber frame|"timber framing"|"timber frame ra...
                                                   17.21.12       timber frame|"timber framing"|"timber frame ra...
...                                                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.29.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
                                                   18.30.04       bgt|"bgt 2018"|"britain got talent"|"britain´s...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       Slot Machine|"win"|"Gambling"|"Big Win"|"raja"...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       YouTube shooter|"YouTube active shooter"|"acti...

                                                                  views_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01          835930
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03          212838
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03          200764
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           79152
                                                   17.21.12          232762
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05          713400
                                                   18.29.04          231906
                                                   18.30.04          476253
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           28973
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04          103513

                                                                  likes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           47058
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            5199
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            5620
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            7761
                                                   17.21.12           15515
...                                                                     ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            4684
                                                   18.29.04            1924
                                                   18.30.04            3417
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            2167
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            1722

                                                                  dislikes_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01               1023
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                542
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                537
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                159
                                                   17.21.12                329
...                                                                        ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                260
                                                   18.29.04                 78
                                                   18.30.04                176
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                175
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                181

                                                                  comment_count_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    8250
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      11
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      45
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    1965
                                                   17.21.12                    3601
...                                                                             ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                     266
                                                   18.29.04                     146
                                                   18.30.04                     240
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                      10
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                      76

                                                                                              thumbnail_link_CAN  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       https://i.ytimg.com/vi/PNn8sECd7io/default.jpg
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       https://i.ytimg.com/vi/DvPW66IFhMI/default.jpg
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       https://i.ytimg.com/vi/EXEaMjFeiEk/default.jpg
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
                                                   17.21.12       https://i.ytimg.com/vi/bYvQmusLaxw/default.jpg
...                                                                                                          ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.29.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
                                                   18.30.04       https://i.ytimg.com/vi/WttN1Z0XF4k/default.jpg
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       https://i.ytimg.com/vi/Wt9Gkpmbt44/default.jpg
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       https://i.ytimg.com/vi/Az72jrKbANA/default.jpg

                                                                  ...  \
title                                              trending_date  ...
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01       ...
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03       ...
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03       ...
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12       ...
                                                   17.21.12       ...
...                                                               ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05       ...
                                                   18.29.04       ...
                                                   18.30.04       ...
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05       ...
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04       ...

                                                                  tags_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01           NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03           NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03           NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12           NaN
                                                   17.21.12           NaN
...                                                                   ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05           NaN
                                                   18.29.04           NaN
                                                   18.30.04           NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05           NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04           NaN

                                                                  views_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                  likes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01            NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03            NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03            NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12            NaN
                                                   17.21.12            NaN
...                                                                    ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05            NaN
                                                   18.29.04            NaN
                                                   18.30.04            NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05            NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04            NaN

                                                                 dislikes_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01              NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03              NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03              NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12              NaN
                                                   17.21.12              NaN
...                                                                      ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05              NaN
                                                   18.29.04              NaN
                                                   18.30.04              NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05              NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04              NaN

                                                                 comment_count_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                   NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                   NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                   NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                   NaN
                                                   17.21.12                   NaN
...                                                                           ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                   NaN
                                                   18.29.04                   NaN
                                                   18.30.04                   NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                   NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                   NaN

                                                                 thumbnail_link_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                    NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                    NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                    NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                    NaN
                                                   17.21.12                    NaN
...                                                                            ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                    NaN
                                                   18.29.04                    NaN
                                                   18.30.04                    NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                    NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                    NaN

                                                                  comments_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                        NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                        NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                        NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                        NaN
                                                   17.21.12                        NaN
...                                                                                ...
😲She Is So Nervous But BLOWS The ROOF After Tak... 18.02.05                        NaN
                                                   18.29.04                        NaN
                                                   18.30.04                        NaN
🚨 BREAKING NEWS 🔴 Raja Live all Slot Channels W... 18.07.05                        NaN
🚨Active Shooter at YouTube Headquarters - LIVE ... 18.04.04                        NaN

                                                                 ratings_disabled_UK  \
title                                              trending_date
!! THIS VIDEO IS NOTHING BUT PAIN !! | Getting ... 18.04.01                      NaN
#1 Fortnite World Rank - 2,323 Solo Wins!          18.09.03                      NaN
#1 Fortnite World Rank - 2,330 Solo Wins!          18.10.03                      NaN
#1 MOST ANTICIPATED VIDEO (Timber Frame House R... 17.20.12                      NaN

# Exercises

### 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [65]:
import pandas as pd

In [66]:
fruits = pd.DataFrame({'Apples':[30], 'Bananas':[21]})
fruits

   Apples  Bananas
0      30       21

### 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [67]:
fruit_sales = pd.DataFrame({'Apples':[35, 41], 'Bananas':[21, 34]}, index=['2017 Sales', '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

### 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [68]:
ingredients = pd.Series(['4 Cups', '1 cup', '2 large', '1 can'], index=['Flour', 'Milk', 'Eggs', 'Spam'], name='Dinner')
ingredients

Flour     4 Cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

### 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://i.imgur.com/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [69]:
reviews = pd.read_csv("datasets/wines/winemag-data_first150k.csv", index_col=0)
reviews

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

### 5.

Run the cell below to create and display a DataFrame called `animals`:

In [70]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [71]:
animals.to_csv("datasets/cows_and_goats.csv")

# Indexing, Selecting & Assigning

In this set of exercises we will work with the [Wine Reviews dataset](https://www.kaggle.com/zynicide/wine-reviews). 
* Run the following cell to load your data and some utility functions (including code to check your answers).

In [72]:
import pandas as pd

reviews = pd.read_csv("datasets/wines/winemag-data-130k-v2.csv", index_col=0)
pd.set_option("display.max_rows", 5)
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### 1.

Select the `description` column from `reviews` and assign the result to the variable `desc`.

In [73]:
desc = reviews.description

Follow-up question: what type of object is `desc`? If you're not sure, you can check by calling Python's `type` function: `type(desc)`.

In [74]:
type(desc)

pandas.core.series.Series

### 2.

Select the first value from the description column of `reviews`, assigning it to variable `first_description`.

In [75]:
first_description = reviews.description.iloc[0]
first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

### 3. 

Select the first row of data (the first record) from `reviews`, assigning it to the variable `first_row`.

In [76]:
first_row = reviews.iloc[0]
first_row

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

### 4.

Select the first 10 values from the `description` column in `reviews`, assigning the result to variable `first_descriptions`.

Hint: format your output as a pandas Series.

In [77]:
first_descriptions = reviews.description.iloc[:10]
first_descriptions

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
                           ...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, Length: 10, dtype: object

### 5.

Select the records with index labels `1`, `2`, `3`, `5`, and `8`, assigning the result to the variable `sample_reviews`.

In other words, generate the following DataFrame:

![](https://i.imgur.com/sHZvI1O.png)

In [78]:
sample_reviews = reviews.iloc[[1, 2, 3, 5, 8]]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel

### 6.

Create a variable `df` containing the `country`, `province`, `region_1`, and `region_2` columns of the records with the index labels `0`, `1`, `10`, and `100`. In other words, generate the following DataFrame:

![](https://i.imgur.com/FUCGiKP.png)

In [79]:
df = reviews[['country', 'province', 'region_1', 'region_2']].iloc[[0, 1, 10, 100]]
df

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

### 7.

Create a variable `df` containing the `country` and `variety` columns of the first 100 records. 

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the tutorial:

> `iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. 
`loc`, meanwhile, indexes inclusively. 

> This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` return 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.iloc[0:999]`.

In [80]:
df = reviews[['country', 'variety']].iloc[0:100]
df

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
..       ...                       ...
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

### 8.

Create a DataFrame `italian_wines` containing reviews of wines made in `Italy`. Hint: `reviews.country` equals what?

In [81]:
italian_wines = reviews.loc[reviews.country == 'Italy']
italian_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129961,Italy,"Intense aromas of wild cherry, baking spice, t...",NaN,90,30.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,COS 2013 Frappato (Sicilia),Frappato,COS
129962,Italy,"Blackberry, cassis, grilled herb and toasted a...",Sàgana Tenuta San Giacomo,90,40.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Cusumano 2012 Sàgana Tenuta San Giacomo Nero d...,Nero d'Avola,Cusumano

### 9.

Create a DataFrame `top_oceania_wines` containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [82]:
top_oceania_wines = reviews.loc[((reviews.country == 'Australia') | (reviews.country == 'New Zealand')) & (reviews.points >= 95)]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie
122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck

# Summary Functions and Maps

### 1.

What is the median of the `points` column in the `reviews` DataFrame?

In [83]:
median_points = reviews.points.median()
print(median_points)

88.0

### 2. 
What countries are represented in the dataset? (Your answer should not include any duplicates.)

In [84]:
countries = reviews.country.unique()
countries

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

### 3.
How often does each country appear in the dataset? Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [85]:
reviews_per_country = reviews.country.value_counts()
reviews_per_country

US          54504
France      22093
            ...
China           1
Slovakia        1
Name: country, Length: 43, dtype: int64

### 4.
Create variable `centered_price` containing a version of the `price` column with the mean price subtracted.

(Note: this 'centering' transformation is a common preprocessing step before applying various machine learning algorithms.)

In [86]:
centered_price = reviews.price - reviews.price.mean()
centered_price

0               NaN
1        -20.363389
            ...
129969    -3.363389
129970   -14.363389
Name: price, Length: 129971, dtype: float64

### 5.
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable `bargain_wine` with the title of the wine with the highest points-to-price ratio in the dataset.

In [87]:
bargain_wine = reviews.title.iloc[(reviews.points / reviews.price).idxmax()]
bargain_wine

'Bandit NV Merlot (California)'

### 6.
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series `descriptor_counts` counting how many times each of these two words appears in the `description` column in the dataset.

In [88]:
tropical = reviews.description.map(lambda d: 'tropical' in d).sum()
fruity = reviews.description.map(lambda d: 'fruity' in d).sum()
descriptor_counts = pd.Series([tropical, fruity], index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

### 7.
We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand - we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars, regardless of points.

Create a series `star_ratings` with the number of stars corresponding to each review in the dataset.

In [95]:
def stars(row):
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1

star_ratings = reviews.apply(stars, axis='columns')
star_ratings

0         2
1         2
         ..
129969    2
129970    2
Length: 129971, dtype: int64

# Grouping and Sorting

### 1.
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [96]:
import pandas as pd

reviews = pd.read_csv("datasets/wines/winemag-data-130k-v2.csv", index_col=0)
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [98]:
reviews_written = reviews.groupby('taster_twitter_handle').taster_twitter_handle.count()
reviews_written

taster_twitter_handle
@AnneInVino        3685
@JoeCz             5147
                   ...
@winewchristina       6
@worldwineguys     1005
Name: taster_twitter_handle, Length: 15, dtype: int64

In [99]:
reviews_written = reviews.groupby('taster_twitter_handle').size()
reviews_written

taster_twitter_handle
@AnneInVino        3685
@JoeCz             5147
                   ...
@winewchristina       6
@worldwineguys     1005
Length: 15, dtype: int64

### 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [106]:
best_rating_per_price = reviews.sort_values(by='price').groupby('price').points.max()
best_rating_per_price

price
4.0       86
5.0       87
          ..
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

### 3.
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [108]:
price_extremes = pd.DataFrame(reviews.groupby('variety').price.agg([min, max]))
price_extremes

              min   max
variety
Abouriou     15.0  75.0
Agiorgitiko  10.0  66.0
...           ...   ...
Çalkarası    19.0  19.0
Žilavka      15.0  15.0

[707 rows x 2 columns]

### 4.
What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [113]:
sorted_varieties = price_extremes.sort_values(by=['min', 'max'], ascending=False)
sorted_varieties

             min    max
variety
Ramisco    495.0  495.0
Terrantez  236.0  236.0
...          ...    ...
Vital        NaN    NaN
Zelen        NaN    NaN

[707 rows x 2 columns]

### 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [116]:
reviewer_mean_ratings = reviews.groupby('taster_name').points.mean()
reviewer_mean_ratings

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
                        ...
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, Length: 19, dtype: float64

Are there significant differences in the average scores assigned by the various reviewers? Run the cell below to use the `describe()` method to see a summary of the range of values.

In [117]:
reviewer_mean_ratings.describe()

count    19.000000
mean     88.233026
           ...
75%      88.975256
max      90.562551
Name: points, Length: 8, dtype: float64

### 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [136]:
country_variety_counts = reviews.groupby(['country', 'variety']).size().sort_values(ascending=False)
country_variety_counts

country    variety
US         Pinot Noir            9885
           Cabernet Sauvignon    7315
                                 ...
Italy      Moscato di Noto          1
Argentina  Barbera                  1
Length: 1612, dtype: int64

# Data Types and Missing Values

### 1. 
What is the data type of the `points` column in the dataset?

In [138]:
dtype = reviews.points.dtype
dtype

dtype('int64')

### 2. 
Create a Series from entries in the `points` column, but convert the entries to strings. Hint: strings are `str` in native Python.

In [140]:
point_strings = reviews.points.astype(str)
point_strings

0         87
1         87
          ..
129969    90
129970    90
Name: points, Length: 129971, dtype: object

### 3.
Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [159]:
n_missing_prices = reviews.price.isnull().sum()
n_missing_prices

8996

### 4.
What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the `region_1` field. This field is often missing data, so replace missing values with `Unknown`. Sort in descending order.  Your output should look something like this:

```
Unknown                    21247
Napa Valley                 4480
                           ...  
Bardolino Superiore            1
Primitivo del Tarantino        1
Name: region_1, Length: 1230, dtype: int64
```

In [166]:
reviews_per_region = reviews.region_1.fillna('Unknown').value_counts()
reviews_per_region

Unknown                     21247
Napa Valley                  4480
                            ...
Criots-Bâtard-Montrachet        1
Montlouis-sur-Loire             1
Name: region_1, Length: 1230, dtype: int64

# Renaming and Combining

## 1.
`region_1` and `region_2` are pretty uninformative names for locale columns in the dataset. Create a copy of `reviews` with these columns renamed to `region` and `locale`, respectively.

In [175]:
renamed = reviews.rename(columns={'region_1':'region', 'region_2':'locale'})
renamed

,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### 2.
Set the index name in the dataset to `wines`.

In [182]:
reindexed = reviews.rename_axis('wines', axis='columns')
reindexed

wines,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

### 3.
The [Things on Reddit](https://www.kaggle.com/residentmario/things-on-reddit/data) dataset includes product links from a selection of top-ranked forums ("subreddits") on reddit.com. Run the cell below to load a dataframe of products mentioned on the */r/gaming* subreddit and another dataframe for products mentioned on the *r//movies* subreddit.

In [195]:
gaming_products = pd.read_csv("datasets/top-things/top-things/reddits/g/gaming.csv")
gaming_products['subreddit'] = 'r/gaming'
movie_products = pd.read_csv("datasets/top-things/top-things/reddits/m/movies.csv")
movie_products['subreddit'] = 'r/movies'

Create a `DataFrame` of products mentioned on *either* subreddit.

In [196]:
combined_products = pd.concat([gaming_products, movie_products])
combined_products

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
...,...,...,...,...,...,...
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies

### 4.
The [Powerlifting Database](https://www.kaggle.com/open-powerlifting/powerlifting-database) dataset on Kaggle includes one CSV table for powerlifting meets and a separate one for powerlifting competitors. Run the cell below to load these datasets into dataframes:

In [202]:
powerlifting_meets = pd.read_csv("datasets/powerlifting/meets.csv")
powerlifting_competitors = pd.read_csv("datasets/powerlifting/openpowerlifting.csv")

Both tables include references to a `MeetID`, a unique key for each meet (competition) included in the database. Using this, generate a dataset combining the two tables into one.

In [203]:


powerlifting_combined = powerlifting_meets.set_index('MeetID').join(powerlifting_competitors.set_index('MeetID'))
powerlifting_combined

,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName,Name,Sex,Equipment,...,WeightClassKg,Squat4Kg,BestSquatKg,Bench4Kg,BestBenchKg,Deadlift4Kg,BestDeadliftKg,TotalKg,Place,Wilks
MeetID,,,,,,,,,,,,,,,,,,,,,
0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...,Angie Belk Terry,F,Wraps,...,60,NaN,47.63,NaN,20.41,NaN,70.31,138.35,1,155.05
0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...,Dawn Bogart,F,Single-ply,...,60,NaN,142.88,NaN,95.25,NaN,163.29,401.42,1,456.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8481,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals,Jeff Bumanglag,M,Multi-ply,...,140,NaN,NaN,NaN,NaN,NaN,320.00,320.00,3,181.85
8481,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals,Shane Hammock,M,Multi-ply,...,140,NaN,NaN,NaN,NaN,NaN,362.50,362.50,2,205.18